### ISSUE TITLE
Call to undefined function dl()

### ISSUE THREAD

**Issue by lorinczdev** [VirgilSecurity/crypto-php#3]
Hello

I'm getting this error:
![image](https://user-images.githubusercontent.com/34649992/48063873-9555c300-e1c6-11e8-8984-86b2cf3819fd.png)

I'm using laravel homestead and php version is PHP 7.2.9-1

**Comment by PetrenkoAnton** [comment]
@lorinczdev , hello

At the moment there are problems with the support of PHP7+
We will try to solve this problem until tomorrow.

Thanks

**Comment by PetrenkoAnton** [comment]
@lorinczdev, hello

Please update virgil/crypto package via composer: **composer require virgil/crypto**

If you have problems installing the crypto library:

- [Download virgil_crypto_2.6.1 archive from the CDN](https://cdn.virgilsecurity.com/virgil-crypto/php/) according to your server operating system and PHP version
- Place **virgil_crypto_php.so** file from the archive into the directory with extensions
- Add string **extension=virgil_crypto_php.so** to the php.ini file
- Restart your web-service (apache or nginx): **sudo service _{apache2 / nginx}_ restart**
- Update virgil/crypto: **composer require virgil/crypto**

Tips:

- PHP version: phpversion() / php --version
- OS Version: PHP_OS
- php.ini and extensions directory: phpinfo() / php -i / php-config --extension_dir

Glad to help you

**Comment by lorinczdev** [comment]
Thanks for the update, all good now!
